# Generated by Django 4.2.4 on 2023-08-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Ciudad',
            field=models.CharField(default='Default City', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='NumeroTelefonico',
            field=models.CharField(default='3015492321', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='Pais',
            field=models.CharField(default='country', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='codigoPostal',
            field=models.IntegerField(default=321321),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(default='Default City', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='identificacion',
            field=models.IntegerField(default=10100, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='nombre', max_length=255),
        ),
    ]
