# Generated by Django 4.2.4 on 2023-08-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_ciudad_user_numerotelefonico_user_pais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identificacion',
            field=models.IntegerField(default=80, unique=True),
        ),
    ]
