# Generated by Django 4.2.4 on 2023-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identificacion',
            field=models.IntegerField(default=81, unique=True),
        ),
    ]
