# Generated by Django 4.2.1 on 2023-08-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_identificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Ciudad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='NumeroTelefonico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='Pais',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='identificacion',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
