# Generated by Django 4.2.1 on 2023-08-25 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_asiento', models.CharField(max_length=255)),
                ('fila', models.CharField(max_length=255)),
                ('letra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fabricante', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('capacidad_pasajeros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_asiento', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('numero', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
                ('asientos_disponibles', models.IntegerField()),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intouch.aerolinea')),
                ('aeropuerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeropuerto_destino', to='intouch.aeropuerto')),
                ('aeropuerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aeropuerto_origen', to='intouch.aeropuerto')),
                ('avion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intouch.avion')),
                ('fecha_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_llegada', to='intouch.horario')),
                ('fecha_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fecha_salida', to='intouch.horario')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intouch.tarifa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('empresa_tarjeta', models.CharField(max_length=255)),
                ('fecha_vencimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intouch.horario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo_reserva', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Reservado', 'Reservado'), ('Comprado', 'Comprado')], default='Reservado', max_length=50)),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intouch.tarjeta')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intouch.vuelo')),
            ],
        ),
    ]
