# Generated by Django 4.2.4 on 2023-08-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intouch', '0005_alter_tarjeta_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha_vencimiento',
            field=models.CharField(help_text='Formato: MM/AA', max_length=5),
        ),
    ]
